"""On-demand environment activation.

The toolchains are deliberately NOT placed on PATH at install time. This module
generates an ``activate.sh`` you can ``source`` only when you want the tools in
the current shell, plus per-arch convenience variables (``CC_AARCH64`` etc.)
that point straight at the right compiler without touching PATH at all.
"""

from __future__ import annotations

import shlex
from pathlib import Path

from . import arch
from .config import Config


def _llvm_bin(cfg: Config) -> Path:
    return cfg.prefix / "llvm" / "bin"


def _llvm_coverage_bin(cfg: Config) -> Path:
    return cfg.prefix / "llvm-coverage" / "bin"


def _gcc_root(cfg: Config) -> Path:
    return cfg.prefix / "gcc"


def _gcc_coverage_root(cfg: Config) -> Path:
    return cfg.prefix / "gcc-coverage"


def _qemu_bin(cfg: Config) -> Path:
    return cfg.prefix / "qemu" / "bin"


def _clang_args(triple: str, sysroot: Path | None, gcc_root: Path | None) -> list[str]:
    args = [f"--target={triple}"]
    if sysroot:
        args.append(f"--sysroot={sysroot}")
    if gcc_root:
        args.append(f"--gcc-toolchain={gcc_root}")
    args.append("-fuse-ld=lld")
    return args


def _clang_wrapper(var: str, args: list[str]) -> list[str]:
    name = f"_cte_clang_{var.lower()}_trunk"
    flags = " ".join(shlex.quote(arg) for arg in args)
    return [
        f"{name}() {{",
        f'  "$CLANG_TRUNK" {flags} "$@"',
        "}",
        f'export CLANG_{var}_TRUNK="{name}"',
    ]


def render(cfg: Config) -> str:
    """Return the text of an activate.sh script."""
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by cte. Source this file to use the toolchains in the",
        "# current shell only. Nothing here is installed system-wide.",
        "",
    ]

    if cfg.llvm.enabled and _llvm_bin(cfg).exists():
        lines.append(f'export CLANG_TRUNK="{_llvm_bin(cfg) / "clang"}"')
        if cfg.llvm.coverage and _llvm_coverage_bin(cfg).exists():
            lines.append(
                f'export CLANG_COVERAGE_TRUNK="{_llvm_coverage_bin(cfg) / "clang"}"'
            )
    # Per-arch compiler/runner pointers (no PATH needed to use these).
    for a in cfg.arches:
        var = a.name.upper().replace("-", "_")
        triple = cfg.target_triple(a)
        sysroot = cfg.sysroot_for(a)
        clang_gcc_root = None
        if cfg.gcc.enabled:
            gcc_root = _gcc_root(cfg) / triple
            clang_gcc_root = gcc_root
            gcc = gcc_root / "bin" / f"{triple}-gcc"
            lines.append(f'export GCC_{var}_TRUNK="{gcc}"')
            lines.append(f'export GCC_TOOLCHAIN_{var}="{gcc_root}"')
            if cfg.gcc.coverage:
                gcc_root = _gcc_coverage_root(cfg) / triple
                gcc = gcc_root / "bin" / f"{triple}-gcc"
                lines.append(f'export GCC_{var}_COVERAGE_TRUNK="{gcc}"')
                lines.append(f'export GCC_COVERAGE_TOOLCHAIN_{var}="{gcc_root}"')
        if cfg.llvm.enabled and _llvm_bin(cfg).exists():
            lines.extend(
                _clang_wrapper(var, _clang_args(triple, sysroot, clang_gcc_root))
            )
        if sysroot:
            lines.append(f'export SYSROOT_{var}="{sysroot}"')
        if cfg.qemu.enabled:
            runner = _qemu_bin(cfg) / f"qemu-{a.qemu_user}"
            lines.append(f'export QEMU_{var}="{runner}"')

    lines.append("")
    return "\n".join(lines)


def write(cfg: Config) -> Path:
    cfg.prefix.mkdir(parents=True, exist_ok=True)
    out = cfg.prefix / "activate.sh"
    out.write_text(render(cfg))
    return out
