"""On-demand environment activation.

The toolchains are deliberately NOT placed on PATH at install time. This module
generates an ``activate.sh`` you can ``source`` only when you want the tools in
the current shell, plus per-arch convenience variables (``CC_AARCH64`` etc.)
that point straight at the right compiler without touching PATH at all.
"""

from __future__ import annotations

from pathlib import Path

from . import arch
from .config import Config


def _llvm_bin(cfg: Config) -> Path:
    return cfg.prefix / "llvm" / "bin"


def _gcc_root(cfg: Config) -> Path:
    return cfg.prefix / "gcc"


def _qemu_bin(cfg: Config) -> Path:
    return cfg.prefix / "qemu" / "bin"


def render(cfg: Config) -> str:
    """Return the text of an activate.sh script."""
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by cte. Source this file to use the toolchains in the",
        "# current shell only. Nothing here is installed system-wide.",
        "",
    ]

    path_dirs = []
    if cfg.llvm.enabled and _llvm_bin(cfg).exists():
        path_dirs.append(str(_llvm_bin(cfg)))
        lines.append(f'export CLANG="{_llvm_bin(cfg) / "clang"}"')
    if cfg.qemu.enabled and _qemu_bin(cfg).exists():
        path_dirs.append(str(_qemu_bin(cfg)))

    # Per-arch compiler/runner pointers (no PATH needed to use these).
    for a in cfg.arches:
        var = a.name.upper().replace("-", "_")
        if cfg.gcc.enabled:
            triple = cfg.target_triple(a)
            gcc = _gcc_root(cfg) / triple / "bin" / f"{triple}-gcc"
            lines.append(f'export GCC_{var}="{gcc}"')
        sysroot = cfg.sysroot_for(a)
        if sysroot:
            lines.append(f'export SYSROOT_{var}="{sysroot}"')
        if cfg.qemu.enabled:
            runner = _qemu_bin(cfg) / f"qemu-{a.qemu_user}"
            lines.append(f'export QEMU_{var}="{runner}"')

    if path_dirs:
        lines.insert(4, 'export PATH="' + ":".join(path_dirs) + ':$PATH"')

    lines.append("")
    return "\n".join(lines)


def write(cfg: Config) -> Path:
    cfg.prefix.mkdir(parents=True, exist_ok=True)
    out = cfg.prefix / "activate.sh"
    out.write_text(render(cfg))
    return out
